### ISSUE TITLE
Change in 0.6.2 breaks usage of source for sudo fragments

### ISSUE THREAD

**Issue by gusson** [Ericsson/puppet-module-sudo#26]
The change in version 0.6.2 breaks usage of the source parameter, because source and content cannot be specified to the resource at the same time. Previously the module worked because the inputs were undef by default, but with this change there will always be something passed as the content parameter. Resulting in the following error if the source parameter is used:

`Error: Failed to apply catalog: Validation of File[10_global] failed: You cannot specify more than one of content, source, target at /etc/puppet/environments/staging/modules-eis/modules/sudo/manifests/fragment.pp:20`

**Comment by ghoneycutt** [comment]
CC: @Phil-Friderici 

Since this module is not yet v1.0.0, breaking changes are allowed. Suggest reviewing its functionality and parameters and making a v1.0.0 release.

**Comment by Phil-Friderici** [comment]
I hope that https://github.com/Ericsson/puppet-module-sudo/pull/27 can satisfy both use cases.
Please give it a try.

**Comment by gusson** [comment]
Tried #27 in a local test environment and it solved the issue.

**Comment by Phil-Friderici** [comment]
@gusson thanks for reporting and verification. Bugfix released in v0.6.3
